version: "2"
services:
  mysql:
#    image: yfix/mysql
    build: .
    ports:
      - 33062:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=yf_for_unit_tests
      - MYSQL_USER=yf_test
      - MYSQL_PASSWORD=yf_test
    volumes:
      - ./docker/etc/mysql/conf.d/override.cnf:/etc/mysql/conf.d/override.cnf
